# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "HFRTopicSummarizer"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true


[default.deploy.parameters]
confirm_changeset = false
stack_name = "hfr_topic_summarizer"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]

[default.deploy.parameters.parameter_overrides]
Environment = "devo"
[devo.deploy.parameters]
stack_name = "hfr-topic-summarizer-devo"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "HFRTopicSummarizer-devo"
region = "eu-west-3"
image_repositories = []
parameter_overrides = [
  "Environment=devo"
]

[prod.deploy.parameters]
stack_name = "hfr-topic-summarizer-prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "HFRTopicSummarizer-prod"
region = "eu-west-3"
image_repositories = []
parameter_overrides = [
  "Environment=prod"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"