AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  HFR Topic Summarizer System

Globals:
  Function:
    Timeout: 150

Parameters: 
  Environment:
    Default: devo
    Description: Environment name
    Type: String
    AllowedValues: 
      - devo
      - prod
  MaxMessageRetries:
    Default: 3
    Description: Maximum number of times a message can be retried
    Type: Number
  LogLevel:
    Type: String
    Default: WARNING
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

Resources:
  # DynamoDB Tables
  TopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-topics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: topic_id
          AttributeType: S
      KeySchema:
        - AttributeName: topic_id
          KeyType: HASH

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: author    
          AttributeType: S
        - AttributeName: timestamp 
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AuthorIndex
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SummariesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-summaries
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: topic_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: topic_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE  # Only need new items

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      # Remove QueueName property
      MessageRetentionPeriod: 1209600  # 14 days

  SummarizationQueue:
    Type: AWS::SQS::Queue
    Properties:
      # Remove QueueName property
      VisibilityTimeout: 160
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxMessageRetries

  # API Gateway
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment

  RequestHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: request_handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      # Removed ReservedConcurrentExecutions
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /summarize
            Method: get
            RestApiId: !Ref ApiDeployment
      Environment:
        Variables:
          SUMMARIES_TABLE: !Ref SummariesTable
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !GetAtt SummariesTable.Arn

  RequestHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: RequestHandlerFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${RequestHandlerFunction}"

  # Stream Processor Lambda - Bridges DynamoDB Streams to SQS
  StreamProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: stream_processor.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt SummariesTable.StreamArn
            StartingPosition: TRIM_HORIZON
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
      Environment:
        Variables:
          QUEUE_URL: !Ref SummarizationQueue
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SummarizationQueue.Arn

  StreamProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: StreamProcessorFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${StreamProcessorFunction}"

  SummaryGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ 
      Handler: summary_generator.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        QueueProcessor:
          Type: SQS
          Properties:
            Queue: !GetAtt SummarizationQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          TOPICS_TABLE: !Ref TopicsTable
          MESSAGES_TABLE: !Ref MessagesTable
          SUMMARIES_TABLE: !Ref SummariesTable
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:BatchGetItem
              Resource: 
                - !GetAtt TopicsTable.Arn
                - !GetAtt MessagesTable.Arn
                - !GetAtt SummariesTable.Arn
                - !Sub "${MessagesTable.Arn}/index/*"
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/*"

  SummaryGeneratorLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: SummaryGeneratorFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${SummaryGeneratorFunction}"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/summarize

  # DynamoDB Tables
  TopicsTableName:
    Description: Name of the Topics table
    Value: !Ref TopicsTable
  TopicsTableArn:
    Description: ARN of the Topics table
    Value: !GetAtt TopicsTable.Arn

  MessagesTableName:
    Description: Name of the Messages table
    Value: !Ref MessagesTable
  MessagesTableArn:
    Description: ARN of the Messages table
    Value: !GetAtt MessagesTable.Arn

  SummariesTableName:
    Description: Name of the Summaries table
    Value: !Ref SummariesTable
  SummariesTableArn:
    Description: ARN of the Summaries table
    Value: !GetAtt SummariesTable.Arn
  SummariesTableStreamArn:
    Description: ARN of the Summaries table stream
    Value: !GetAtt SummariesTable.StreamArn

  # Queue URLs
  DeadLetterQueueUrl:
    Description: URL of the Dead Letter Queue
    Value: !Ref DeadLetterQueue
  DeadLetterQueueArn:
    Description: ARN of the Dead Letter Queue
    Value: !GetAtt DeadLetterQueue.Arn

  SummarizationQueueUrl:
    Description: URL of the main processing Queue
    Value: !Ref SummarizationQueue
  SummarizationQueueArn:
    Description: ARN of the main processing Queue
    Value: !GetAtt SummarizationQueue.Arn

  # Lambda Functions
  RequestHandlerFunctionArn:
    Description: ARN of the Request Handler Lambda function
    Value: !GetAtt RequestHandlerFunction.Arn
  RequestHandlerFunctionRole:
    Description: IAM Role created for Request Handler Lambda function
    Value: !GetAtt RequestHandlerFunctionRole.Arn

  StreamProcessorFunctionArn:
    Description: ARN of the Stream Processor Lambda function
    Value: !GetAtt StreamProcessorFunction.Arn
  StreamProcessorFunctionRole:
    Description: IAM Role created for Stream Processor Lambda function
    Value: !GetAtt StreamProcessorFunctionRole.Arn

  SummaryGeneratorFunctionArn:
    Description: ARN of the Summary Generator Lambda function
    Value: !GetAtt SummaryGeneratorFunction.Arn
  SummaryGeneratorFunctionRole:
    Description: IAM Role created for Summary Generator Lambda function
    Value: !GetAtt SummaryGeneratorFunctionRole.Arn