AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  HFRTopicSummarizer  

Globals:
  Function:
    Timeout: 150

Parameters: 
  Environment:
    Default: devo
    Description: Environment name
    Type: String
    AllowedValues: 
      - devo
      - prod

Resources:
  # Topics Table
  TopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-topics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: topic_id
          AttributeType: S
      KeySchema:
        - AttributeName: topic_id  # format: "cat#subcat#post"
          KeyType: HASH

  # Messages Table
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # Summaries Table (with sort key)
  SummariesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-hfr-summaries
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: topic_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: topic_id  # format: "cat#subcat#post"
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE

  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment

  HFRTopicSummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hfr_topic_summarizer/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        HFRTopicSummarizer:
          Type: Api
          Properties:
            Path: /hfr_topic_summarizer
            Method: get
            RestApiId: !Ref ApiDeployment
      Environment:
        Variables:
          environment: !Ref Environment
          TOPICS_TABLE: !Ref TopicsTable
          MESSAGES_TABLE: !Ref MessagesTable
          SUMMARIES_TABLE: !Ref SummariesTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource: 
                - !GetAtt TopicsTable.Arn
                - !GetAtt MessagesTable.Arn
                - !GetAtt SummariesTable.Arn
                - !Sub "${TopicsTable.Arn}/index/*"
                - !Sub "${MessagesTable.Arn}/index/*"
                - !Sub "${SummariesTable.Arn}/index/*"

Outputs:
  HFRTopicSummarizerApi:
    Description: API Gateway endpoint URL for HFRTopicSummarizer function
    Value: !Sub https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/hfr_topic_summarizer/
  HFRTopicSummarizerFunction:
    Description: HFRTopicSummarizer Bot Lambda Function ARN
    Value: !GetAtt HFRTopicSummarizerFunction.Arn
  HFRTopicSummarizerFunctionIamRole:
    Description: Implicit IAM Role created for HFRTopicSummarizer function
    Value: !GetAtt HFRTopicSummarizerFunctionRole.Arn
  TopicsTableName:
    Description: Name of the Topics DynamoDB table
    Value: !Ref TopicsTable
  MessagesTableName:
    Description: Name of the Messages DynamoDB table
    Value: !Ref MessagesTable
  SummariesTableName:
    Description: Name of the Summaries DynamoDB table
    Value: !Ref SummariesTable
